### ISSUE TITLE
Implicit identity maps do not generate appropriate DependenceExpressions

### ISSUE THREAD

**Issue by JCampbellBradley** [CSU-CS-Melange/alpha-language#120]
Expressions of the form
```let     Y = X;```
do not generate DependenceExpressions when parsed into an AST. Assuming Y is a one dimensional variable, one would expect the AST to be equivalent to that of the expression
```let     Y[i] = X[i];```

**Comment by rajopadhye** [comment]
There are two equivalent ASTs:

Y = A  // The RHS expression AST has a single node
Y = A.(i->i)  // The RHS expression AST is a dependence node with the function being the identity.

Both are legal.  So where should the fix be?

1. Modify all visitors (e.g., PRDG generator) to handle this corner case
2. Modify the parser to add the identity node 
3. disallow the first syntax

I'm not sure which is the best solution

**Comment by JCampbellBradley** [comment]
I would lean towards #2, but I've reached out to Louis to ask what his thoughts are.

**Comment by lnarmour** [comment]
I think option 2 makes sense, though it may be better/easier to just modify Normalize to wrap variable expression nodes (with parents that are not dependence expressions) in an identity dependence expression. Then have other transformations assume that they are working with a normalized program (codegen should be doing this anyway).

@JCampbellBradley, if you want to modify the parser, take a look at the AlphaLoader class:
https://github.com/CSU-CS-Melange/alpha-language/blob/main/bundles/alpha.loader/src/alpha/loader/AlphaLoader.java#L77

You could either just add a single transformation step before the root is returned in `loadAlpha` or figure out where in the parser construction step the VariableExpression node is explicitly created and insert a DependenceExpression node instead. I haven’t touched this so I’m not exactly where you would do this, but you should be able to find by stepping thru `loadAlpha`.
