### ISSUE TITLE
Handle implicit effectively saturated constraints

### ISSUE THREAD

**Issue by lnarmour** [CSU-CS-Melange/alpha-language#20]
The following set is not handled correctly by the face lattice:
```
[N] -> { [i, j, k, l] : N >= 11 and i <= 3 and 2 + i <= j <= N and i <= k <= -2 + 2i and -2 + i + j <= l < i + j }
```

This is really a 1D subspace embedded in 4D. Barvinok’s card (to count the number of integer points) reports this as 1D (i.e., the polynomial’s maximum degree on N is 1)...
```
$0 := [N] -> { (-22 + 6 * N) : N >= 11 }
```

…but the current implementation of the face lattice can only identify a single effectively saturated constraint:
```
Inequality constraints (ISLMatrix):
5
6
0 -1 0 0 0 3 
0 -1 1 0 0 -2 
1 0 -1 0 0 0 
0 -1 0 1 0 0 
0 2 0 -1 0 -2 

Equality constraints (ISLMatrix):
0
6

Thick equality constraints (ISLMatrix):
2
6
0 -1 -1 0 1 2 
0 1 1 0 -1 -1 
```
and incorrectly reports this as 3D (4 indices - 0 equaltities - 1 pair of thick equalities). I’m not sure how to handle this.

The challenge is to recognize that `i` is bound by constants from `2<=i<=3` even though there is no explicit lower bound on `i`. The inequality `i<=3` appears explicitly but the constraint that `0<=i` comes implicitly from the constraints `i <= k <= -2 + 2i`. The only way for `i<=-2+2i` is when `2<=i`.

**Comment by ryanjob42** [comment]
Completed with PR #23
