### ISSUE TITLE
Merge clean face lattice implementation

### ISSUE THREAD

**Issue by lnarmour** [CSU-CS-Melange/alpha-language#28]
The `simplification-clean` branch has the clean version of the face lattice (which uses ISLConstraints instead of ISLMatrix objects). We had previous fixes to the face lattice to handle “thick faces” and “implicit effectively saturated constraints” (issue #17 and issue #20).

Verify that the face lattice implementation in `simplification-clean` also handles this.

**Comment by ryanjob42** [comment]
We also need to make sure issue #22 is also present with this code.
