### ISSUE TITLE
Use Maven for Unit Testing

### ISSUE THREAD

**Issue by ryanjob42** [CSU-CS-Melange/alpha-language#50]
Instead of the existing way to run the unit tests in the GitHub Actions workflow, it seems that we can just run `mvn clean test` (or just `mvn test`) to run all the unit tests. We should see if this will work for us.

This would require:
1. Check that this does in fact run all the unit tests (and not that some are missing).
    1. If there are any missing, I think we can fix that by adding it to one of the `pom.xml` files.
2. Check that this is compatible with the code coverage reporting.
3. Update the GitHub workflow file to use this instead
4. Optional: we may be able to switch to a simpler container/runner for building everything.

**Comment by JCampbellBradley** [comment]
This issue may be more work than it's worth, and PR #88 drastically reduces the time tests take- the only issue is that we have to continually add any new tests to the pom file, which is easy enough to do. Consider closing?

**Comment by ryanjob42** [comment]
Yes, let's just stick with the solution from PR #88.
