### ISSUE TITLE
Unbounded reduction bodies

### ISSUE THREAD

**Issue by lnarmour** [CSU-CS-Melange/alpha-language#58]
Consider the following program:
```
affine unboundedBody [N] -> {  : N > 0 }
	inputs Y : [N]
	outputs X : [N]
	let
		X = reduce(+, (i,j->i+j), Y[i+j]);
.
```

The context domain of the reduction body is `[N] -> { [i, j] : 0<=i+j<N }` which is unbounded. Consequently, it is not possible to generate loops for the body. First of all, is this program even well defined? It seems like no, but I’m not sure.

Either (1) the program is well defined and we need to figure out how to bound the context domain of the reduction body, or (2) the program is not well defined and the parser should throw an exception.

**Comment by rajopadhye** [comment]
This should be an illegal program.  Reductions whose output has an infinite domain are one, but where the preimage of any result by the project function and the body content domain is unbounded are no allowed.  CheckProgram should catch and flag this
